### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by yakovd33** [nicktogo/coeditor#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro Education
**Thrown From**: [coeditor](https://github.com/nicktogo/coeditor) package 0.2.4

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At path.js:7

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at /packages/coeditor/lib/router.js:59:30)
    at emitTwo (events.js:111:20)
    at WebSocket.emit (events.js:191:7)
    at Receiver._receiver.onmessage (/packages/coeditor/node_modules/ws/lib/WebSocket.js:146:54)
    at Receiver.dataMessage (/packages/coeditor/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/packages/coeditor/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/packages/coeditor/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/packages/coeditor/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/packages/coeditor/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -0:58.7.0 coeditor:toggle (input.hidden-input)
     -0:58.3.0 core:paste (input.hidden-input)
     -0:58.1.0 core:confirm (input.hidden-input)
     -0:50.9.0 coeditor:toggle (input.hidden-input)
  3x -0:50.5.0 core:paste (input.hidden-input)
     -0:45.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
coeditor 0.2.4 
motepair 0.24.0 
```

**Comment by nicktogo** [comment]
Sorry, I'm busy with my exam recently. I will try to fix it when I am free. Or you could open a PR for it. Thanks.

**Comment by nicktogo** [comment]
Hi, I now start to work on it, but it seems work fine on my Atom, could you please add more steps to reproduce this issue? Thank you very much.

**Comment by nicktogo** [comment]
Closing this issue as no follow up. People can reopen this issue if they have the same problem.
