### ISSUE TITLE
Uncaught TypeError: Cannot read property 'aborted' of null

### ISSUE THREAD

**Issue by lucasribeiroufrj** [nicktogo/coeditor#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [coeditor](https://github.com/nicktogo/coeditor) package 0.2.6

### Stack Trace

Uncaught TypeError: Cannot read property 'aborted' of null

```
At /Users/lucasribeiroufrj/.atom/packages/coeditor/node_modules/ws/lib/WebSocket.js:640

TypeError: Cannot read property 'aborted' of null
    at ClientRequest._req.on (/packages/coeditor/node_modules/ws/lib/WebSocket.js:640:18)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketCloseListener (_http_client.js:285:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -0:13.9.0 command-palette:toggle (div.tool-panel.tree-view)
     -0:10.5.0 core:confirm (input.hidden-input)
     -0:10.3.0 coeditor:toggle (div.tool-panel.tree-view)
     -0:09.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-realtime-collaboration 0.7.1 
coeditor 0.2.6 
gpp-compiler 3.0.7 
language-gnuplot-atom 0.2.0 
language-latex 1.1.0 
my-package 0.0.0 
open-recent 5.0.0 
script 3.15.0 
xatom-debug 1.6.7 
xatom-debug-nodejs 0.9.3 
```

**Comment by nicktogo** [comment]
It seems to me that the coeditor client cannot connect to the server or the websocket connect just broke down. Can you tell me more info about how you use the server and client?

**Comment by lucasribeiroufrj** [comment]
Hello nick,

I just installed and tried the steps described in he readme. The problem occurs on the server side right after typing the session id.

ps.: The console only says 
   WebSocket Server Created.
No more outputs. I also tried the whole process on ubuntu.
